	FUNCTION MYREALTOCHAR ( RE, CFXY )

C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    MYREALTOCHAR
C   PRGMMR: ATOR            ORG: NP12       DATE: 2007-01-19
C
C ABSTRACT:  THIS FUNCTION LOOKS FOR AND RETURNS A VALID FXY NUMBER
C   FROM WITHIN THE GIVEN INPUT STRING.  THE FXY NUMBER MAY BE IN
C   FORMAT OF EITHER FXXYYY OR F-XX-YYY WITHIN THE INPUT STRING, BUT
C   IT IS ALWAYS RETURNED IN FORMAT FXXYYY UPON OUTPUT.
C
C PROGRAM HISTORY LOG:
C 2007-01-19  J. ATOR    -- ORIGINAL AUTHOR
C
C USAGE:    MYREALTOCHAR ( STR, CFXY )
C   INPUT ARGUMENT LIST:
C     RE      - Data as real
C
C   OUTPUT ARGUMENT LIST:
C     CFXY     - CHARACTER*8: data as character
C     MYREALTOCHAR  - INTEGER: RETURN CODE:
C                       0 = normal return
C                      -1 = Error
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  PORTABLE TO ALL PLATFORMS
C
C$$$

	REAL*8          RE,RVAL
	CHARACTER*8	CFXY,CVAL
        EQUIVALENCE     (RVAL,CVAL)


	MYREALTOCHAR = -1

        RVAL = RE
        CFXY = CVAL

	MYREALTOCHAR = 0

	RETURN
	END
